export const COURSE_HELPER = [
  {
    id: 0,
    title: "Introduction to Superfluid: Stream money every second",
    subTxt:
      "Tokenomics describes how a token`s use affects its price. You will learn: - What are tokenomics? - What makes a token valuable? - The principles of tokenomics",
    img: "/img/CommonComponents/courseQuizes/product1.png",
    vector: "/img/CommonComponents/courseQuizes/vector.svg",
    lang: "English",
    date: "29 JUL, 2022",
    level: "beginner",
    category: "security",
    time: "8 min",
    price: "free",
  },
  {
    id: 1,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/courseQuizes/product2.png",
    vector: "/img/CommonComponents/courseQuizes/vector.svg",
    lang: "English",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8 min",
    price: "$19.00",
  },
  {
    id: 2,
    title: "Introduction to Superfluid: Stream money every second",
    subTxt:
      "Tokenomics describes how a token`s use affects its price. You will learn: - What are tokenomics? - What makes a token valuable? - The principles of tokenomics",
    img: "/img/CommonComponents/courseQuizes/product3.png",
    vector: "/img/CommonComponents/courseQuizes/vector.svg",
    lang: "English",
    date: "29 JUL, 2022",
    level: "beginner",
    category: "security",
    time: "8 min",
    price: "$19.00",
  },
  {
    id: 3,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/courseQuizes/product4.png",
    vector: "/img/CommonComponents/courseQuizes/vector.svg",
    lang: "English",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8 min",
    price: "free",
  },
  {
    id: 4,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/courseQuizes/product5.png",
    vector: "/img/CommonComponents/courseQuizes/vector.svg",
    lang: "English",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8 min",
    price: "$19.00",
  },
  {
    id: 5,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/courseQuizes/product6.png",
    vector: "/img/CommonComponents/courseQuizes/vector.svg",
    lang: "English",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8 min",
    price: "$19.00",
  },
  {
    id: 6,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/courseQuizes/product7.png",
    vector: "/img/CommonComponents/courseQuizes/vector.svg",
    lang: "English",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8 min",
    price: "free",
  },
];

export default {
  COURSE_HELPER,
};
