export const data = [
  {
    id: 0,
    title: "Introduction to Superfluid: Stream money every second",
    subTxt:
      "Tokenomics describes how a token`s use affects its price. You will learn: - What are tokenomics? - What makes a token valuable? - The principles of tokenomics",
    img: "/img/CommonComponents/CourseQuizes/product1.png",
    vector: "/img/CommonComponents/CourseQuizes/vector.svg",
    date: "29 JUL, 2022",
    level: "beginner",
    category: "security",
    time: "8",
  },
  {
    id: 1,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/CourseQuizes/product2.png",
    vector: "/img/CommonComponents/CourseQuizes/vector.svg",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8",
  },
  {
    id: 2,
    title: "Introduction to Superfluid: Stream money every second",
    subTxt:
      "Tokenomics describes how a token`s use affects its price. You will learn: - What are tokenomics? - What makes a token valuable? - The principles of tokenomics",
    img: "/img/CommonComponents/CourseQuizes/product3.png",
    vector: "/img/CommonComponents/CourseQuizes/vector.svg",
    date: "29 JUL, 2022",
    level: "beginner",
    category: "security",
    time: "8",
  },
  {
    id: 3,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/CourseQuizes/product4.png",
    vector: "/img/CommonComponents/CourseQuizes/vector.svg",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8",
  },
  {
    id: 4,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/CourseQuizes/product5.png",
    vector: "/img/CommonComponents/CourseQuizes/vector.svg",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8",
  },
  {
    id: 5,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/CourseQuizes/product6.png",
    vector: "/img/CommonComponents/CourseQuizes/vector.svg",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8",
  },
  {
    id: 6,
    title: "Understanding Hop Protocol",
    subTxt:
      "This mini-course will teach you everything you need to know about Hop Protocol",
    img: "/img/CommonComponents/CourseQuizes/product7.png",
    vector: "/img/CommonComponents/CourseQuizes/vector.svg",
    date: "29 JUL, 2022",
    level: "Pro",
    category: "Crypto",
    time: "8",
  },
];
